build: add rules for checking header file, golangci-lint and go modules
kubernetes-sigs/zeitgeist pull request #19
Opened 2021-01-08 13:13 UTC by cpanato

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Add rules to run some checks similar to other repositories

Test infra PR to add prow jobs: 

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/assign @justaugustus @saschagrunert

2021-01-08 22:04 UTC, justaugustus requested changes
One nit!

2021-01-08 22:04 UTC, justaugustus commented on hack/verify-boilerplate.sh
> +VERSION=v0.1.1
```suggestion
VERSION=v0.2.0
```

2021-01-09 15:31 UTC, cpanato commented on hack/verify-boilerplate.sh
> +VERSION=v0.1.1
done. PTAL

2021-01-11 07:43 UTC, saschagrunert approved these changes
/lgtm

2021-01-11 07:45 UTC, merged